### ISSUE TITLE
Optional?

### ISSUE THREAD

**Issue by zvezdochiot** [dr-ni/helmert3d#10]
https://github.com/dr-ni/helmert3d/blob/37c7b4b47ec8611948e619039aac23a0a5012bc7/README.md?plain=1#L76
* `xyz_src_infilename`, `xyz_dest_infilename` - required
* `[parms_outfilename]` - optional

https://github.com/dr-ni/helmert3d/blob/37c7b4b47ec8611948e619039aac23a0a5012bc7/README.md?plain=1#L81
* `xyz_src_infilename`, `param_infilename` - required
* `[xyz_transformed_outfilename]` - optional

https://github.com/dr-ni/helmert3d/blob/37c7b4b47ec8611948e619039aac23a0a5012bc7/README.md?plain=1#L86
* {`blh`|`xyz`}, `src_infilename`, `ellipsoid_infilename` - required
* `[outfilename]` - optional

https://github.com/dr-ni/helmert3d/blob/37c7b4b47ec8611948e619039aac23a0a5012bc7/README.md?plain=1#L91
* `xyz_dest_infilename`, `xyz_transformed_infilename` - required
* `[xyz_diff_outfilename]` - optional

**Comment by dr-ni** [comment]
oh you are right, can you fix it in all man1  and in Readme.md
I have to go sleeping now...

**Comment by zvezdochiot** [comment]
Hi @dr-ni .

Yes, norm. Just so that there is no misunderstanding. It will wait.
