### ISSUE TITLE
Links?

### ISSUE THREAD

**Issue by zvezdochiot** [dr-ni/helmert3d#4]
Maybe add a link: 
* https://github.com/Geo-Linux-Calculations/gnumeric-ols/blob/master/spreadsheets/conformaltrans/helmert3d.gnumeric

**Comment by dr-ni** [comment]
what do you mean exactly?

**Comment by zvezdochiot** [comment]
@dr-ni say:
>what do you mean exactly?

:page_facing_up: Readme.md :
```
...

## Links
* :information_source: [Wikipedia](https://en.wikipedia.org/wiki/Helmert_transformation)
* :chart_with_downwards_trend: [Gnumeric spreadsheet](https://github.com/Geo-Linux-Calculations/gnumeric-ols/blob/master/spreadsheets/conformaltrans/helmert3d.gnumeric)

----

https://github.com/dr-ni/helmert3d
```

See also: :page_facing_up: [jpeg-quantsmooth: Alternatives and comparison](https://github.com/ilyakurdyukov/jpeg-quantsmooth#alternatives-and-comparison)

**Comment by dr-ni** [comment]
I think links are not so much interesting here.
wikipedia is known eveywhere
the other link is empty or pointing to a fork?

**Comment by zvezdochiot** [comment]
@dr-ni say:
>the other link is empty or pointing to a fork?

What does empty mean? And not a fork, but an alternative.

**Comment by dr-ni** [comment]
if I click on it there is opening an empty page

**Comment by zvezdochiot** [comment]
@dr-ni say:
>if I click on it there is opening an empty page

Really? 
```
gnumeric-ols/spreadsheets/conformaltrans/helmert3d.gnumeric 
1 contributor 
10.7 KB
[Download](https://github.com/Geo-Linux-Calculations/gnumeric-ols/raw/master/spreadsheets/conformaltrans/helmert3d.gnumeric)
[View raw](https://github.com/Geo-Linux-Calculations/gnumeric-ols/blob/master/spreadsheets/conformaltrans/helmert3d.gnumeric?raw=true)
```
Not?

**Comment by dr-ni** [comment]
there is no readme and no description so that one can see what this is.

![2021-03-08-184945_1280x720_scrot](https://user-images.githubusercontent.com/68241100/110381675-199c0780-805a-11eb-827f-8b36bc2ac850.png)

**Comment by dr-ni** [comment]
is this issue solved?

**Comment by zvezdochiot** [comment]
Yes, this is already useless.

**Comment by zvezdochiot** [comment]
[geofindkey](https://github.com/Geo-Linux-Calculations/geofindkey) in version [3.0](https://github.com/Geo-Linux-Calculations/geofindkey/releases/tag/3.0) include geohelmert3d (alternative).
