### ISSUE TITLE
Ellipsoid?

### ISSUE THREAD

**Issue by zvezdochiot** [dr-ni/helmert3d#7]
Hi @dr-ni .

At the moment there is only one ellipsoid: 
```txt
GRS80 6378137.0 6356752.3141
```
A list of commonly used ellipsoids known to me: 
```txt
BESSEL 6377397.155 6356078.962822
GRS80 6378137.0 6356752.3141
GSK2011 6378136.5 6356751.758
KRASOVSKIY 6378245.0 6356863.018773
PZ90 6378136.0 6356752.3142
WGS84 6378137.0 6356752.314245
```
Add those that you see fit (and wherever you see fit) to this repo. 

PS: Should we change the form of `a b` to the more common `a 1/f`, where `b = a * (1 - f)`? See:
* https://en.wikipedia.org/wiki/Bessel_ellipsoid
* https://en.wikipedia.org/wiki/SK-42_reference_system
* https://en.wikipedia.org/wiki/PZ-90
* https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84

**Comment by dr-ni** [comment]
yes, common formats make sense

do you know LGS21?

**Comment by zvezdochiot** [comment]
@dr-ni say:
>do you know LGS21?

Unknow.

**Comment by zvezdochiot** [comment]
See https://proj.org/usage/ellipsoids.html . Defined by (`a rf f b`). See https://proj.org/usage/projections.html . Defined by (`a b`). I'll leave it as it is for now. 

https://github.com/dr-ni/helmert3d/commit/975d1b13ad629ec18ba0e385c1aff45195e5a9c6
