### ISSUE TITLE
Pandora's box

### ISSUE THREAD

**Issue by dr-ni** [dr-ni/helmert3d#8]
we have now opened Pandora's box. Should we support other projections, too?

https://en.wikipedia.org/wiki/List_of_map_projections

**Comment by zvezdochiot** [comment]
Relax, @dr-ni .

We don't have a single projection algorithm.

B-L-H <-> X-Y-Z translation is a translation from one kind of 3D coordinates to another kind of 3D coordinates. 3D!!!

It's just that X-Y-Z depends only on the center point and three vectors, and B-L-H depends on the whole 3D figure - an ellipsoid. But both of these systems are 3D, without projections. 

Dont worry, be happy.

**Comment by dr-ni** [comment]
yes, but this is only working for ellipsoid projection methods, isn't it?

**Comment by zvezdochiot** [comment]
Not, @dr-ni .

This works for ellipsoids. Without any projections.

**Comment by dr-ni** [comment]
yes but there are many many other methods (=projection methods whithout ellipsoid projections)
so this is only! for ellipsoids

**Comment by zvezdochiot** [comment]
Not, @dr-ni .

We do not use any (ANI!) projections.

**Comment by dr-ni** [comment]
I know but what is with all those other stuff that is not based on ellipsoidal coordinate systems

**Comment by zvezdochiot** [comment]
@dr-ni say:
>but what is with all those other stuff

* https://proj.org
* https://github.com/Geo-Linux-Calculations/geofindkey
* https://github.com/Geo-Linux-Calculations/gnumeric-ols/tree/master/spreadsheets/conformaltrans
* https://github.com/Geo-Linux-Calculations/gauss-kruger
* https://github.com/Geo-Linux-Calculations/geoconformimage
* https://github.com/ImageProcessing-ElectronicPublications/photoquick-examples/tree/main/plugins/transform/geometry

**Comment by dr-ni** [comment]
off course - this was what I was thinking about
if we support ellipsoids we also should support any other common local/global coordinate transformation

**Comment by zvezdochiot** [comment]
@dr-ni  say:
>we also should support any other common local/global coordinate transformation

Not. I introduced the B-L-H <-> X-Y-Z transformation, only because the B-L-H representation is more common and this transformation is not projective.

See also [Geomatics Guidance Note 7, part 2 Coordinate Conversions & Transformations including Formulas (version 57, September 2019) 373-07-02.pdf](https://github.com/dr-ni/helmert3d/files/7610048/Geomatics.Guidance.Note.7.part.2.Coordinate.Conversions.Transformations.including.Formulas.version.57.September.2019.373-07-02.pdf)

**Comment by dr-ni** [comment]
nice paper :-)
to avoid further missunderstanding - should we use instead of blh lat lon h

**Comment by zvezdochiot** [comment]
@dr-ni say:
>instead of blh lat lon h

And what is the short entry? This one doesn't go anywhere. 
* https://www.latlong.net/
* https://en.wikipedia.org/wiki/Geographic_coordinate_system

"The "latitude" (abbreviation: Lat., φ, or phi)"  
"The "longitude" (abbreviation: Long., λ, or lambda)"  

In Russia geodesic "latitude" - B, geodesic "longitude" - L.

**Comment by dr-ni** [comment]
in germany also b=Breite l=Länge h=Höhe
maybe the russian was taking over the german 
but nowadys rather everywhere lat and lon are common
I can later add this to the manual and we leave blh...

**Comment by dr-ni** [comment]
is this a good reference?
we could add it?

https://www.bluemarblegeo.com/knowledgebase/global-mapper-19/Ellipsoids.htm

**Comment by zvezdochiot** [comment]
@dr-ni say:
>https://www.bluemarblegeo.com/knowledgebase/global-mapper-19/Ellipsoids.htm

Everything is much easier to do: 
[ellipsoids.txt.gz](https://github.com/dr-ni/helmert3d/files/7621402/ellipsoids.txt.gz)

**Comment by dr-ni** [comment]
are spheres also working with helmeltrans

**Comment by dr-ni** [comment]
shall we add for all a separate file?

**Comment by zvezdochiot** [comment]
@dr-ni say:
>are spheres also

Yes. They are sometimes used to machine spherical triangles. This is an approximation, but very good.

@dr-ni say:
>shall we add for all a separate file?

Crazy?! Dirty repository! Who needs to create it himself. Just put this file in a "prominent place".

**Comment by dr-ni** [comment]
ok, so we add the file to the ellipsoids folder?

**Comment by zvezdochiot** [comment]
@dr-ni say:
>ok, so we add the file to the ellipsoids folder?

Not. To the documentation. Next to README.md 

PS: Crazy thought: Shouldn't we make a separate helmert3d-data, hang up a banner there about collecting transformation matrices? Such a warehouse "with the world by thread".

**Comment by dr-ni** [comment]
could be also possible. Do you mean the helmparms3d output format?

**Comment by zvezdochiot** [comment]
@dr-ni say:
>Do you mean the helmparms3d output format?

Yes.

**Comment by dr-ni** [comment]
but has to be checked always if correct and no spam

**Comment by zvezdochiot** [comment]
@dr-ni say:
>but has to be checked always if correct and no spam

Issues are always open. Kind people will tell you.

PS: I said that the idea is delusional.

**Comment by dr-ni** [comment]
ok can you open it?
I'll add the file to the repo, anyway

**Comment by zvezdochiot** [comment]
@dr-ni say:
>ok can you open it?

I am a disgusting "marketer". This business will not go with me in charge. Let's leave crazy ideas to posterity.

**Comment by dr-ni** [comment]
ok

**Comment by zvezdochiot** [comment]
Hi @dr-ni 

See also https://github.com/SammyB428/GFC/blob/24aaf24c3145f46e62a4d48ce2c36c75e49c155a/GFC/CEarth.cpp#L827-L1003

**Comment by dr-ni** [comment]
updated

**Comment by dr-ni** [comment]
I'm asking myself if this upgrade is a reliable one?

many precisions are so unrealistic, for example WGS84:
WGS_84 6378137.0 6356752.3142451793
0.0000000003 m precisions????!!!
for example 1 Å = 100 pm = 0.1 nm = 10^{−10} m
The Ångström is used in particular in crystallography and chemistry to be able to work with "simple" numerical values. 1 Å is the typical order of magnitude for atomic radii and distances between atoms in crystal structures and bond lengths in molecules. Even the moon forces the earth surface around ±50 cm

**Comment by zvezdochiot** [comment]
@dr-ni . The initial values are `a` and `1/f`. I already wrote about this. The polar axis `b` is calculated `b=a*(1-f)`. Number of characters for storage only `f`.
